name: Test App Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        container: 
            image: node:20
        steps:
        - uses: actions/checkout@v3
          with: 
            node-version: 20
        - name: Run tests
          run: |
            npm ci
            npm run build
